[project]
name = "python-uv-workspaces-example"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "lib/*",
    "apps/*",
    "t",
]
